export PS1="\[\033[34m\]\u\[\033[00m\]:\[\033[34m\]\W \[\033[36m\]@\h\[\033[00m\]$ "
#export SCALA_HOME=/Library/Scala/default
#export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
#export MAVEN_HOME="/opt/local/maven-1.1"
#export MYSQL_HOME=/usr/local/mysql
#export GRADLE_HOME=/opt/local/share/java/gradle
alias ls="ls -G"
export GREP_OPTIONS='--color=auto'
